server:
  port: 80

# 定时任务
serverless:
  timer: "*/2 * * * * ?"
  spaces:
    default:
      libs: D:\\workspace\\GitHub\\SilenceShine\\jvm-serverless\\lib
      functions: D:\\workspace\\GitHub\\SilenceShine\\jvm-serverless\\serverless-demo\\src\\main\\java

logging:
  level:
    io.github.SilenceShine.jvm.serverless: debug

